set(_CATKIN_CURRENT_PACKAGE "man_description")
set(man_description_VERSION "0.0.0")
set(man_description_MAINTAINER "stav.42 <stav.42@todo.todo>")
set(man_description_PACKAGE_FORMAT "2")
set(man_description_BUILD_DEPENDS "urdf" "controller_manager" "joint_state_publisher" "robot_state_publisher")
set(man_description_BUILD_EXPORT_DEPENDS "urdf" "controller_manager" "joint_state_publisher" "robot_state_publisher")
set(man_description_BUILDTOOL_DEPENDS "catkin")
set(man_description_BUILDTOOL_EXPORT_DEPENDS )
set(man_description_EXEC_DEPENDS "urdf" "controller_manager" "joint_state_publisher" "robot_state_publisher")
set(man_description_RUN_DEPENDS "urdf" "controller_manager" "joint_state_publisher" "robot_state_publisher")
set(man_description_TEST_DEPENDS )
set(man_description_DOC_DEPENDS )
set(man_description_URL_WEBSITE "")
set(man_description_URL_BUGTRACKER "")
set(man_description_URL_REPOSITORY "")
set(man_description_DEPRECATED "")